# You can configure the type of authorization you will be using here
# options are [saml, database, disabled]
#
# If you choose to use database authenication
# you'll want to first start off with authentication disabled
# you can then navigate to /admin and create users
# once you have users created, youll be able to sign in normally with them
#
# auth_type: saml
#
# If you are using SAML, you'll need to have:
#
# saml_issuer: <My App>
# saml_name_identifier_format: <"urn:oasis:names:tc:SAML:2.0:nameid-format:transient">

