# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

playground:
  secret_key_base: 9e7c5bc270eea113a263a475bd38c97fb2f5691e4b1cd2d7155f46a4df770c6005edfc032815a98c830fd5dc9c3935193279ab33bca8aa81bc567585232c0847

development:
  secret_key_base: cb9a5aecfb471728b1d2eee49c26ccf648388e0e709f683b4d2dd2a57a4a1c5dde88a8d852143f524f1fb33b9ee3beac306cb64f7ec365340bbb8b72bbbe71ca

test:
  secret_key_base: 6e430dd05a2077ca4c4e4920e9334c5c68d136aae42d4eca6f438228e15b871c0ffc08f9ff3d320358be23bf0bb7748282ac55a306f581bf567420067e133f15

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
