smtp_common: &smtp_common
  user_name: stmp_username
  domain: email.yourorg.com
  address: smtp.someservice.com
  port: 555
  authentication: !ruby/sym plain
  enable_starttls_auto: true

development:
  smpt_settings:
    <<: *smtp_common
  from: bi-alerts@email.yourorg.com
  default_url_host: localhost:3000

test:
  smpt_settings:
    <<: *smtp_common
  from: bi-alerts@email.yourorg.com

staging:
  smpt_settings:
    <<: *smtp_common
  from: bi-alerts@email.yourorg.com
  default_url_host: staging-aleph.yourorg.com

production:
  smpt_settings:
    <<: *smtp_common
  from: bi-alerts@email.yourorg.com
  default_url_host: aleph.yourorg.com
